on:
  push:
    branches:
      - master





jobs:
  build:
    runs-on: ubuntu-latest


    steps:
      - name: 'Before'
        run: ls

      - name: 'Testing Printing'
        run: echo Abdelrahman

      - uses: actions/checkout@v3
      - name: 'Before'
        run: ls
